package satm;

public enum Event {

    ATM_CARD_SWIPE,
    ENTER_NUMBER,
    BUTTON_A,
    BUTTON_B,
    BUTTON_C,
    INSERT_DEPOSIT_ENVELOPE,
    REMOVE_CASH

//    VALID_ATM_CARD_SWIPE,
//    INVALID_ATM_CARD_SWIPE,
//    CORRECT_PIN,
//    FAILED_PIN,
//    CHOOSE_BALANCE,
//    CHOOSE_DEPOSIT,
//    ENTER_DEPOSIT_AMOUNT,
//    INSERT_DEPOSIT_ENVELOPE,
//    CHOOSE_WITHDRAWAL,
//    VALID_WITHDRAWAL_AMOUNT,
//    WITHDRAWAL_AMOUNT_NOT_MULTIPLE_10,
//    WITHDRAWAL_AMOUNT_EXCEEDS_BALANCE,
//    WITHDRAWAL_AMOUNT_EXCEEDS_DAILY_LIMIT,
//    REMOVE_CASH,
//    YES,
//    NO

}
